config/routes.rb
MadLibsApp::Application.routes.draw do
  
  root to: "mad_libs#index"
  resources :mad_libs

end

app/models/mad_lib.rb
class MadLib < ActiveRecord::Base
  attr_accessible :adjective, :noun, :proper_noun, :verb
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mad_libs_controller.rb
class MadLibsController < ApplicationController
  def index
  	#@mad_libs = MadLib.all
    @mad_libs = MadLib.paginate(page: params[:page], per_page: 4).order('created_at DESC') 
    @mad_lib = MadLib.new

  	respond_to do |format|
  	  format.html
  	end
  end

  def create 	
  	@mad_lib = MadLib.create(params[:mad_lib])

  	respond_to do |format|
  	  format.js
  	end
  end

  def destroy
  	@mad_lib = MadLib.delete(params[:id])
    @id = params[:id]

  	respond_to do |format|
  	  format.js
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mad_libs_helper.rb
module MadLibsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MadLibsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mad_libs/_mad_lib.html.erb
<li data-id='<%= mad_lib.id %>'><%= mad_lib.proper_noun %> <%= mad_lib.verb %> over the <%= mad_lib.adjective %> <%= mad_lib.noun %>.
❦ <%= link_to "reject", mad_lib_path(mad_lib), :method => "delete", :remote => true %> 
</li>

app/views/mad_libs/create.html.erb
<h1>MadLibs#create</h1>
<p>Find me in app/views/mad_libs/create.html.erb</p>

app/views/mad_libs/create.js.erb
$("#madlibs").append('<%= escape_javascript(render @mad_lib) %>');

// clear fields after form submit
$('#mad_lib_noun').val("");
$('#mad_lib_proper_noun').val("");
$('#mad_lib_verb').val("");
$('#mad_lib_adjective').val("");

app/views/mad_libs/destroy.html.erb
<h1>MadLibs#destroy</h1>
<p>Find me in app/views/mad_libs/destroy.html.erb</p>

app/views/mad_libs/destroy.js.erb
var id = "<%= @id %>";
var remove_it = 'li[data-id=' + id +']'
$(remove_it).remove();

app/views/mad_libs/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Delius+Swash+Caps' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door' rel='stylesheet' type='text/css'>
<div id="container">
<div id="title">Mad Libs!</div>
	<div id="da_form">
	<%= form_for(@mad_lib, remote: true) do |f| %>
		<div class="fields">
		<%= f.label :noun %>
		<%= f.text_field :noun, placeholder: :noun, autofocus: true, required: true %><br>
		<%= f.label :proper_noun %>
		<%= f.text_field :proper_noun, placeholder: "proper noun", required: true %><br>
		<%= f.label :adjective %>
		<%= f.text_field :adjective, placeholder: "adjective", required: true %><br>
		<%= f.label :verb %> (past tense!)
		<%= f.text_field :verb, placeholder: "verb", required: true %>
		</div>
		<%#= f.submit %>
		<button type="submit" class="css3button">make mad lib</button>
	<% end %>
	</div>

<!-- list of all madlibs -->
<!--   t.string   "verb"
    t.string   "noun"
    t.string   "adjective"
    t.string   "proper_noun" -->
	<div id="madlibs">
		
		<% @mad_libs.each do |mad_lib| %>
		
	</li>
	  	<%= render "mad_lib", :mad_lib => mad_lib %>
		<% end %>
		
	</div>
<%= will_paginate @mad_libs %>
</div>